apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-safety-backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        #중요: 아래 주소는 ECR 창고 주소입니다. )
        # 나중에 백엔드 깃액션이 latest 부분을 새로운 커밋 해시 번호로 덮어씌웁니다!
        image: 549328952175.dkr.ecr.ap-northeast-2.amazonaws.com/smart-safety-backend:6560cb952199274e2f631bb3e676eaa641c679c0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        # 데이터베이스 설정
        - name: DB_URL
          value: "jdbc:postgresql://smart-safety-db-prod.cleq04iqogz6.ap-northeast-2.rds.amazonaws.com:5432/postgres?sslmode=require"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-safety-secrets
              key: DB_PASSWORD
        # Redis 설정
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-safety-secrets
              key: REDIS_PASSWORD
        # 보안 설정
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smart-safety-secrets
              key: JWT_SECRET
        - name: AES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: smart-safety-secrets
              key: AES_SECRET_KEY
