apiVersion: v1
kind: Service
metadata:
  name: smart-safety-frontend-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31905
    protocol: TCP
  selector:
    app: smart-safety-frontend
